### ISSUE TITLE
Greska prilikom citanja sa kartice. Poziv EidStartup nije uspeo, kod greske: -3

### ISSUE THREAD

**Issue by vciric** [DeanMilojevic/CelikNet#1]
Pozdrav,

Konstantno dobijam poruku "Greska prilikom citanja sa kartice. Poziv EidStartup nije uspeo, kod greske: -3", šta može da bude problem? Konstantno puca Validate u 22 liniji u Interop.cs.

**Comment by DeanMilojevic** [comment]
Kada sam se igrao sa ovim, bilo je tesko razumeti tacno sta koja greska znaci bez reflektovanja originalnog koda od API-a. 
Problemi koje sam ja u pocetku imao: razlika izmedju API-a i chip-a u kartici, problem sa verzijama API-a (kao sto sam istoj klasi napisao, zvanicna dokumentacija je podrzavala v2 API-a), problemi sa nekim citacima... 
Imao sam negde bookmark-ovan source code od samog API-a (mislim da je cak bilo na spanskom i da sam koristio google translate) gde je bilo moguce videti error code-ove. Probacu da pronadjem source code od API-a, ako se budem setio gde je, pa da pogledam u kom slucaju baca tu gresku.
Pozdrav i sa srecom.
